#!/bin/bash
#
# @file install
# ☆  Install for assembling and installing vcloud-client
# @author Alister Lewis-Bowen <alister@different.com>
#

#
# Document root
#
SRC=www
#
# A timestamp
#
TIMESTAMP=$(date +"%F-%H%M%S")
#
# Cell target directory
#
OB_TARGET=/opt/vmware/vcloud-director/system/com/vmware/vcloud/ui-vcloud-webapp/1.0.0
#
# Cell war file name
#
WAR=ui-vcloud-webapp-1.0.0.war
#
# Back up war file name
#
BACKUP=${WAR}.$TIMESTAMP.bak
#
# Source Tree target directory
#
ST_TARGET=ui/ssui/ui-vcloud-webapp/target/ui-vcloud-webapp-1.0.0
#
# Source Tree base directory
#
ST_BASE=${VCLOUD_SRC_ROOT:-'.'}
#
# Default vCloud JS SDK src directory
#
SDK_SRC=${VCLOUD_JS_SDK_ROOT:-'../vcloud-js-sdk'};
#
# Watch poll time (seconds)
#
WATCH_POLL=1

function _failWith {
    echo 'failed'; echo $1; echo
    exit 0
}

function _mkdir {
    [ -d $1 ] && rm -fR $1
    mkdir -p $1 2>/dev/null
}

function _setSdkSrcDir {
    echo -n "Where is your vcloud-js-sdk src tree? [$SDK_SRC] "
    read srcDir
    [ ! -z "$srcDir" ] && SDK_SRC=$srcDir;
    echo
}

function _copySdk {
    echo -n 'Copying vCloud JS SDK... '
    [ ! -d $SDK_SRC ] && _failWith "Unable to find a SDK src tree directory at $SDK_SRC"
    cp $SDK_SRC/vcloud-js-sdk*.js $SRC/js/lib/
    echo 'done'
    echo
}

function _installIntoOfficialBuild {
    echo -n 'Installing SilverLining into your vCD cell...'
    [ ! -d $OB_TARGET ] && _failWith "Unable to find the war file in $OB_TARGET"
    cd $OB_TARGET
    cp $WAR ../$BACKUP
    unzip $WAR &>/dev/null
    rm -f $WAR
    echo -n '...'
    cp -r $SRC .
    echo -n '...'
    zip -urg ../$WAR * &>/dev/null
    echo -n '...'
    rm -fR ./*
    mv ../$WAR .
    cd - >/dev/null
    echo ' done'
    echo
}

function _setVcdSrcDir {
    echo -n "Where is your vCD src tree? [$ST_BASE] "
    read srcDir
    [ ! -z "$srcDir" ] && ST_BASE=$srcDir
    echo
}

function _installIntoP4Source {
    echo -n 'Installing into your src tree... '
    local target=$ST_BASE/$ST_TARGET
    [ ! -d $target ] && _failWith "Unable to find a src tree directory at $target"
    local dir=$target/vcloud-js-sdk-test
    _mkdir $dir
    cp -r $SRC/* $dir/
    echo 'done'
    echo
}

function _watchAndInstall {
    echo 'Watching for any changes. Quit using [cntl-C].'
    echo
    local changes=''
    while true; do
        changes=$(find $SRC -mtime ${WATCH_POLL}s)
        [[ ! -z "$changes" ]] && {
            echo '['$(date +"%F-%H%M%S")"] These following things changed:"
            echo "$changes"
            _installIntoP4Source
        }
        sleep $WATCH_POLL;
    done
}

function _help {
    local helpText="
Install script for vcloud-client.

With no option this script will install into a vCD cell.

Usage: make <option>
-cs, --copy-sdk        copy the SDK lib from a local vCloud JS SDK src tree
                       and place into doc root
-id, --install-dev     install doc root into a vCD src tree
-ic, --install-cell    install doc root into a vCD cell (default)
-w, --watch            install when anything in the doc root changes
"
    echo "$helpText"
}

case "$1" in
    --help|-h)
        _help
        ;;
    #
    # Copy SDK lib from local SDK src tree and place them into this src tree
    #
    --copy-sdk|-cs)
        _setSdkSrcDir
        _copySdk
        ;;
    #
    # Watch doc root and install on any change
    #
    --watch|-w)
        _setVcdSrcDir
        _watchAndInstall
        ;;
    #
    # Copy doc root into correct position in vCD src tree
    #
    --install-dev|-id)
        _setVcdSrcDir
        _installIntoP4Source
        echo "Installed successfully at $ST_TARGET"
        echo 'Go to http://[your_cell_host_and_port]/cloud/vcloud-js-sdk-test/index.html'
        echo
        ;;
    #
    # Copy doc root into correct position of a running vCD cell
    #
    --install-cell|-ic|*)
        _installIntoOfficialBuild
        echo "Installed successfully. Please restart the cell to complete the \
installation, e.g. 'service vmware-vcd restart'."
        echo
        echo "NOTE: To back-out this change, just move $OB_TARGET/../$BACKUP \
into $OB_TARGET/$WAR and restart the cell."
echo
        ;;
esac
